version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run: npm install -g pnpm
      - run: pnpm install
      - run: npx nx affected:build
      - run: npx nx affected:test
    cache:
      paths:
        - ~/.pnpm-store
        - node_modules
        - .nx/cache
  build-mobile:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run: npm install -g pnpm expo-cli
      - run: pnpm install
      - run: cd apps/mobile && expo install
      - run: npx nx build mobile --platform ios
    cache:
      paths:
        - ~/.pnpm-store
        - node_modules
        - .nx/cache
workflows:
  build-and-test:
    jobs:
      - build
      - build-mobile
